/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Driver;
import java.sql.ResultSet;
import java.sql.Statement;

@WebServlet("/hello")
public class App extends HttpServlet {
    
    @Override 
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {

        String url = "jdbc:mariadb://db:3306/studydb";
        String user = "webapp";
        String password = "password";

        try {
            Driver driver = new org.mariadb.jdbc.Driver();
            DriverManager.registerDriver(driver);

            try(Connection connection = DriverManager.getConnection(url, user, password)){
                String sql = "SELECT id, organization_code, name FROM studydb.users";

                Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery(sql);

                while (resultSet.next()) {
                    response.getWriter().println(
                        resultSet.getInt("id") + " " +
                        resultSet.getString("organization_code") + " " +
                        resultSet.getString("name")
                    );
                }

            response.getWriter().println("DB Connection OK!");
            }
        } catch (SQLException e) {
            response.getWriter().println("DB Connection failed!");
            e.printStackTrace();
        }
      }
}