name: Docker build

on:
push:
branch: ["master"]

jobs:
docker-build:
runs-on: ubntu-latest

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Build Docker image
  
  run: docker image -f ./app/Dockerfile -t simple-web-app .
