name: TEST-SSM

on:
    push:
        branches: ["master"]

permissions:
    id-token: write
    contents: read

env:
    AWS_REGION: ap-northeast-1

jobs:
    test-ssm:
        runs-on: ubuntu-latest